import { Category, MenuItem, AddOn, Order } from '@/types/coffee';

export const CATEGORIES: Category[] = [
  {
    id: 'all',
    name: 'Semua Menu',
    icon: 'Coffee',
    description: 'Jelajahi seluruh sajian minuman dan makanan pilihan kami',
  },
  {
    id: 'espresso',
    name: 'Espresso & Milk',
    icon: 'CupSoda',
    description: 'Racikan berbasis espresso dengan susu creamy dan sirup artisanal',
  },
  {
    id: 'manual-brew',
    name: 'Manual Brew',
    icon: 'Flame',
    description: 'Seduhan manual biji kopi single origin nusantara pilihan',
  },
  {
    id: 'cold-brew',
    name: 'Cold Brew & Tea',
    icon: 'Sparkles',
    description: 'Seduhan dingin segar 16 jam & artisan tea yang menyegarkan',
  },
  {
    id: 'pastry',
    name: 'Pastry & Bakery',
    icon: 'Croissant',
    description: 'Kue dan pastry freshly baked setiap pagi',
  },
  {
    id: 'snacks',
    name: 'Snacks & Toast',
    icon: 'Utensils',
    description: 'Cemilan gurih dan hidangan pengganjal lapar yang pas',
  },
];

export const ADD_ONS: AddOn[] = [
  { id: 'extra_shot', name: 'Extra Espresso Shot', price: 6000 },
  { id: 'caramel_syrup', name: 'Syrup Caramel Salé', price: 5000 },
  { id: 'vanilla_syrup', name: 'Syrup French Vanilla', price: 5000 },
  { id: 'whipped_cream', name: 'Artisan Whipped Cream', price: 4000 },
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'kro-01',
    name: 'Kroma Signature Palm Latte',
    category: 'espresso',
    description: 'Espresso blend Arabika Gayo & Flores, susu segar lembut, dan gula aren organik cair kental.',
    tastingNotes: ['Brown Sugar', 'Creamy Butter', 'Roasted Hazelnut'],
    price: 28000,
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?q=80&w=800&auto=format&fit=crop',
    isBestSeller: true,
    available: true,
    allowCustomization: true,
  },
  {
    id: 'kro-02',
    name: 'Spanish Sea Salt Latte',
    category: 'espresso',
    description: 'Perpaduan espresso pekat dengan susu kental manis dan foam krim gurih sea salt lembut di atasnya.',
    tastingNotes: ['Sweet Caramel', 'Flaky Sea Salt', 'Rich Crema'],
    price: 34000,
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?q=80&w=800&auto=format&fit=crop',
    isBestSeller: true,
    isBaristaPick: true,
    available: true,
    allowCustomization: true,
  },
  {
    id: 'kro-03',
    name: 'Flat White Velvet',
    category: 'espresso',
    description: 'Double ristretto dipadukan microfoam susu kukus dengan tekstur selembut sutra.',
    tastingNotes: ['Dark Chocolate', 'Toasted Almond', 'Velvety Finish'],
    price: 30000,
    image: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?q=80&w=800&auto=format&fit=crop',
    available: true,
    allowCustomization: true,
  },
  {
    id: 'kro-04',
    name: 'Manual Brew V60 Single Origin',
    category: 'manual-brew',
    description: 'Biji kopi pilihan Gayo Pantan Musara proses Anaerobic Natural dengan karakter rasa kompleks.',
    tastingNotes: ['Bergamot', 'Wild Strawberry', 'Cane Sugar'],
    price: 36000,
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop',
    isBaristaPick: true,
    available: true,
    allowCustomization: false,
  },
  {
    id: 'kro-05',
    name: 'Japanese Drip Iced Coffee',
    category: 'manual-brew',
    description: 'V60 pour-over yang langsung menetes ke es batu kristal, menghasilkan rasa kopi buah yang tajam dan bersih.',
    tastingNotes: ['Peach', 'Jasmine', 'Crisp Lemonade'],
    price: 35000,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    available: true,
    allowCustomization: false,
  },
  {
    id: 'kro-06',
    name: 'Cold Brew Citrus Fizz',
    category: 'cold-brew',
    description: 'Kopi seduh dingin 18 jam dengan sparkling water, irisan lemon kering, dan sirup yuzu wangi.',
    tastingNotes: ['Bright Citrus', 'Sparkling Tonic', 'Floral Cacao'],
    price: 33000,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=800&auto=format&fit=crop',
    isBestSeller: true,
    available: true,
    allowCustomization: true,
  },
  {
    id: 'kro-07',
    name: 'Kyoto Classic Black Cold Brew',
    category: 'cold-brew',
    description: 'Kopi hitam cold brew metode tetes lambat, aroma cokelat pekat tanpa rasa asam berlebih.',
    tastingNotes: ['Dark Cocoa', 'Molasses', 'Smooth Body'],
    price: 29000,
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?q=80&w=800&auto=format&fit=crop',
    available: true,
    allowCustomization: true,
  },
  {
    id: 'kro-08',
    name: 'Golden Almond Croissant',
    category: 'pastry',
    description: 'Flaky French croissant berlapis mentega panggang dengan isian almond frangipane dan taburan almond panggang.',
    price: 28000,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=800&auto=format&fit=crop',
    isBestSeller: true,
    available: true,
    allowCustomization: false,
  },
  {
    id: 'kro-09',
    name: 'Cinnamon Roll Cream Cheese',
    category: 'pastry',
    description: 'Roti gulung kayu manis harum disiram lelehan frosting cream cheese vanilla hangat.',
    price: 26000,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop',
    available: true,
    allowCustomization: false,
  },
  {
    id: 'kro-10',
    name: 'Truffle Parmesan Fries',
    category: 'snacks',
    description: 'Kentang goreng renyah dibalut minyak white truffle Italia, keju parmesan parut, dan dipping aioli garlic.',
    price: 32000,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?q=80&w=800&auto=format&fit=crop',
    isBestSeller: true,
    available: true,
    allowCustomization: false,
  },
  {
    id: 'kro-11',
    name: 'Smoked Beef Melt Sourdough Toast',
    category: 'snacks',
    description: 'Roti sourdough artisan panggang dengan keju cheddar leleh, irisan smoked beef gurih, dan mustard mayo.',
    price: 38000,
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?q=80&w=800&auto=format&fit=crop',
    isBaristaPick: true,
    available: true,
    allowCustomization: false,
  },
  {
    id: 'kro-12',
    name: 'Pisang Goreng Wijen Karamel',
    category: 'snacks',
    description: 'Pisang kepok manis berbalut adonan renyah biji wijen, disajikan dengan saus karamel gula aren cair.',
    price: 24000,
    image: 'https://images.unsplash.com/photo-1621236378699-8597faf6a173?q=80&w=800&auto=format&fit=crop',
    available: true,
    allowCustomization: false,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'KRO-801',
    customerName: 'Dimas Prasetyo',
    customerPhone: '08129876543',
    orderType: 'dine_in',
    tableNumber: 'Meja 04',
    items: [
      {
        id: 'kro-01-c1',
        menuItem: MENU_ITEMS[0],
        quantity: 2,
        customization: {
          sugarLevel: 'less',
          iceLevel: 'normal',
          milkOption: 'oatmilk',
          selectedAddOns: ['extra_shot'],
          notes: 'Tolong jangan terlalu dingin',
        },
        itemPrice: 40000,
        totalPrice: 80000,
      },
      {
        id: 'kro-08-c1',
        menuItem: MENU_ITEMS[7],
        quantity: 1,
        customization: {
          sugarLevel: 'normal',
          iceLevel: 'none',
          milkOption: 'dairy',
          selectedAddOns: [],
          notes: 'Hangatkan sebentar',
        },
        itemPrice: 28000,
        totalPrice: 28000,
      },
    ],
    subtotal: 108000,
    tax: 10800,
    total: 118800,
    paymentMethod: 'qris',
    paymentStatus: 'paid',
    status: 'new',
    notes: 'Sedotan kertas 2 ya mas',
    createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(), // 4 mins ago
    updatedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
  },
  {
    id: 'KRO-799',
    customerName: 'Siti Rahma',
    customerPhone: '08138765432',
    orderType: 'dine_in',
    tableNumber: 'Meja 09',
    items: [
      {
        id: 'kro-02-c1',
        menuItem: MENU_ITEMS[1],
        quantity: 1,
        customization: {
          sugarLevel: 'normal',
          iceLevel: 'less',
          milkOption: 'dairy',
          selectedAddOns: [],
        },
        itemPrice: 34000,
        totalPrice: 34000,
      },
      {
        id: 'kro-10-c1',
        menuItem: MENU_ITEMS[9],
        quantity: 1,
        customization: {
          sugarLevel: 'normal',
          iceLevel: 'none',
          milkOption: 'dairy',
          selectedAddOns: [],
        },
        itemPrice: 32000,
        totalPrice: 32000,
      },
    ],
    subtotal: 66000,
    tax: 6600,
    total: 72600,
    paymentMethod: 'cash',
    paymentStatus: 'paid',
    status: 'brewing',
    notes: 'Saus aioli dipisah',
    createdAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
  },
  {
    id: 'KRO-795',
    customerName: 'Budi Santoso',
    customerPhone: '08571234567',
    orderType: 'takeaway',
    items: [
      {
        id: 'kro-06-c1',
        menuItem: MENU_ITEMS[5],
        quantity: 2,
        customization: {
          sugarLevel: 'low',
          iceLevel: 'normal',
          milkOption: 'dairy',
          selectedAddOns: [],
        },
        itemPrice: 33000,
        totalPrice: 66000,
      },
    ],
    subtotal: 66000,
    tax: 6600,
    total: 72600,
    paymentMethod: 'qris',
    paymentStatus: 'paid',
    status: 'ready',
    createdAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'KRO-788',
    customerName: 'Alya Natasha',
    customerPhone: '08123456789',
    orderType: 'dine_in',
    tableNumber: 'Meja 02',
    items: [
      {
        id: 'kro-04-c1',
        menuItem: MENU_ITEMS[3],
        quantity: 1,
        customization: {
          sugarLevel: 'none',
          iceLevel: 'none',
          milkOption: 'dairy',
          selectedAddOns: [],
        },
        itemPrice: 36000,
        totalPrice: 36000,
      },
      {
        id: 'kro-09-c1',
        menuItem: MENU_ITEMS[8],
        quantity: 1,
        customization: {
          sugarLevel: 'normal',
          iceLevel: 'none',
          milkOption: 'dairy',
          selectedAddOns: [],
        },
        itemPrice: 26000,
        totalPrice: 26000,
      },
    ],
    subtotal: 62000,
    tax: 6200,
    total: 68200,
    paymentMethod: 'card',
    paymentStatus: 'paid',
    status: 'completed',
    createdAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];
