import { Category, MenuItem, AddOn, Order } from '@/types/coffee';

export const CATEGORIES: Category[] = [
  {
    id: 'all',
    name: 'Semua Produk',
    icon: 'Coffee',
    description: 'Jelajahi seluruh sajian minuman dan makanan pilihan kami',
  },
  {
    id: 'coffee',
    name: 'Coffee',
    icon: 'CupSoda',
    description: 'Racikan kopi pilihan berbasis espresso dan susu segar',
  },
  {
    id: 'fusion-coffee',
    name: 'Fusion Coffee',
    icon: 'Sparkles',
    description: 'Kombinasi unik kopi dengan sari buah segar dan soda',
  },
  {
    id: 'milk-tea',
    name: 'Milk Tea Series',
    icon: 'CupSoda',
    description: 'Teh pilihan dipadu kelembutan susu artisanal',
  },
  {
    id: 'macchiato',
    name: 'Macchiato Series',
    icon: 'Flame',
    description: 'Lapisan foam macchiato lembut di atas minuman favorit',
  },
  {
    id: 'milk-series',
    name: 'Milk Series',
    icon: 'Sparkles',
    description: 'Susu segar berpadu aneka rasa lezat tanpa kafein',
  },
  {
    id: 'tea-series',
    name: 'Tea Series',
    icon: 'Sparkles',
    description: 'Teh seduh segar yang menenangkan dan menyegarkan',
  },
  {
    id: 'manual-brew',
    name: 'Manual Brew (V60)',
    icon: 'Flame',
    description: 'Seduhan biji kopi single origin dengan teknik manual filter',
  },
  {
    id: 'cold-brew',
    name: 'Cold Brew',
    icon: 'Sparkles',
    description: 'Kopi seduh dingin selama 16 jam dengan rasa lembut dan manis alami',
  },
  {
    id: 'lokale-in-250',
    name: 'Brew Bean IN 250ml',
    icon: 'Coffee',
    description: 'Kemasan botol praktis 250ml siap bawa',
  },
  {
    id: 'lokale-in-1l',
    name: 'Brew Bean IN 1 Liter',
    icon: 'Coffee',
    description: 'Ukuran 1 liter pas dinikmati bersama teman atau keluarga',
  },
  {
    id: 'pastry',
    name: 'Pastry & Bakery',
    icon: 'Croissant',
    description: 'Kue dan pastry freshly baked setiap pagi (Croissant, Roll, dll)',
  },
  {
    id: 'toast',
    name: 'Toast & Sandwich',
    icon: 'Utensils',
    description: 'Roti panggang sourdough melt dan aneka sandwich lezat',
  },
  {
    id: 'main-dish',
    name: 'Main Dish',
    icon: 'Utensils',
    description: 'Menu makanan utama yang lezat dan mengenyangkan',
  },
  {
    id: 'side-dish',
    name: 'Side Dish & Snacks',
    icon: 'Utensils',
    description: 'Camilan renyah gurih pelengkap nongkrong (Fries, Pisang Goreng, dll)',
  },
  {
    id: 'dessert',
    name: 'Dessert & Sweet',
    icon: 'Sparkles',
    description: 'Hidangan penutup manis pelepas dahaga dan peneman santai',
  },
];

export const ADD_ONS: AddOn[] = [
  { id: 'extra_shot', name: 'Extra Espresso Shot', price: 6000 },
  { id: 'caramel_syrup', name: 'Syrup Caramel', price: 5000 },
  { id: 'vanilla_syrup', name: 'Syrup Vanilla', price: 5000 },
  { id: 'whipped_cream', name: 'Macchiato Foam', price: 5000 },
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'lok-01',
    name: 'Oat Latte',
    category: 'coffee',
    description: 'Espresso blend pilihan berpadu gurih dan lembutnya susu oat premium.',
    tastingNotes: ['Creamy Oat', 'Nutty', 'Smooth Finish'],
    price: 28000,
    image: '/images/hero-latte.png',
    isBestSeller: true,
    available: true,
    allowCustomization: true,
  },
  {
    id: 'lok-02',
    name: 'Caffe Latte',
    category: 'coffee',
    description: 'Perpaduan klasik espresso kaya rasa dengan steamed milk lembut berbusa.',
    tastingNotes: ['Velvety Milk', 'Rich Crema', 'Balanced'],
    price: 26000,
    image: '/images/hero-latte.png',
    isBestSeller: true,
    available: true,
    allowCustomization: true,
  },
  {
    id: 'lok-03',
    name: 'Americano',
    category: 'coffee',
    description: 'Espresso ganda disajikan dengan air murni dan es batu kristal segar.',
    tastingNotes: ['Bold Roast', 'Dark Cocoa', 'Crisp'],
    price: 22000,
    image: '/images/prod-americano.png',
    isBaristaPick: true,
    available: true,
    allowCustomization: true,
  },
  {
    id: 'lok-04',
    name: 'lokale Signature Macchiato',
    category: 'macchiato',
    description: 'Kopi susu andalan lokale dengan lapisan cold foam macchiato manis gurih di atasnya.',
    tastingNotes: ['Sweet Foam', 'Salted Caramel', 'Velvety'],
    price: 32000,
    image: '/images/prod-macchiato.png',
    isBestSeller: true,
    available: true,
    allowCustomization: true,
  },
  {
    id: 'lok-05',
    name: 'Kopi Susu lokale',
    category: 'coffee',
    description: 'Kopi susu gula aren khas racikan rahasia lokale yang creamy dan legit.',
    tastingNotes: ['Gula Aren', 'Creamy', 'Comforting'],
    price: 24000,
    image: '/images/hero-latte.png',
    isBestSeller: true,
    available: true,
    allowCustomization: true,
  },
  {
    id: 'lok-06',
    name: 'Kopi Susu Raya',
    category: 'coffee',
    description: 'Sensasi kopi susu lebih pekat dengan aroma roasted bean yang dominan.',
    tastingNotes: ['Deep Roast', 'Condensed Milk', 'Strong'],
    price: 25000,
    image: '/images/hero-latte.png',
    available: true,
    allowCustomization: true,
  },
  {
    id: 'lok-07',
    name: 'Lemon Punch Americano',
    category: 'fusion-coffee',
    description: 'Kesegaran espresso hitam dipadukan sentuhan jus lemon segar dan soda berkilau.',
    tastingNotes: ['Citrus Zest', 'Tangy Sweet', 'Effervescent'],
    price: 28000,
    image: '/images/prod-lemon.png',
    isBaristaPick: true,
    available: true,
    allowCustomization: true,
  },
  {
    id: 'lok-08',
    name: 'Berry Splash Americano',
    category: 'fusion-coffee',
    description: 'Americano segar berpadu manis asam sirup buah berry asli di lapisan dasar.',
    tastingNotes: ['Wild Berry', 'Fruity Sweet', 'Refreshing'],
    price: 29000,
    image: '/images/prod-berry.png',
    isBestSeller: true,
    available: true,
    allowCustomization: true,
  },
  {
    id: 'lok-09',
    name: 'lokale Milk Tea',
    category: 'milk-tea',
    description: 'Teh hitam pilihan diseduh dengan susu segar dan sentuhan karamel lembut.',
    tastingNotes: ['Ceylon Tea', 'Smooth Cream', 'Floral'],
    price: 24000,
    image: '/images/hero-latte.png',
    available: true,
    allowCustomization: true,
  },
  {
    id: 'lok-10',
    name: 'Matcha Macchiato',
    category: 'macchiato',
    description: 'Uji matcha Jepang harum berpadu foam macchiato tebal yang manis gurih.',
    tastingNotes: ['Authentic Matcha', 'Sweet Foam', 'Earthy'],
    price: 30000,
    image: '/images/hero-matcha.png',
    isBaristaPick: true,
    available: true,
    allowCustomization: true,
  },
  {
    id: 'lok-11',
    name: 'lokale-IN Kopi Susu Raya',
    category: 'lokale-in-250',
    description: 'Kopi Susu Raya dalam kemasan botol kaca 250ml praktis, siap diminum kapan saja.',
    tastingNotes: ['Chilled', 'Ready to Drink', 'Rich'],
    price: 35000,
    image: '/images/prod-bottle.png',
    available: true,
    allowCustomization: false,
  },
  {
    id: 'lok-12',
    name: 'Butter Croissant',
    category: 'pastry',
    description: 'Croissant panggang mentega Prancis berlapis renyah dengan aroma wangi menggoda.',
    tastingNotes: ['Flaky', 'Pure Butter', 'Golden Crisp'],
    price: 25000,
    image: '/images/prod-croissant.png',
    isBestSeller: true,
    available: true,
    allowCustomization: false,
  },
  {
    id: 'lok-13',
    name: 'Truffle Fries',
    category: 'side-dish',
    description: 'Kentang goreng renyah dengan minyak white truffle Italia dan taburan parmesan.',
    price: 30000,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?q=80&w=800&auto=format&fit=crop',
    available: true,
    allowCustomization: false,
  },
  {
    id: 'lok-14',
    name: 'Smoked Beef Toast',
    category: 'main-dish',
    description: 'Roti sourdough panggang dengan keju cheddar leleh dan irisan smoked beef gurih.',
    price: 38000,
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?q=80&w=800&auto=format&fit=crop',
    available: true,
    allowCustomization: false,
  },
];


export const INITIAL_ORDERS: Order[] = [
  {
    id: 'KRO-801',
    customerName: 'Dimas Prasetyo',
    customerPhone: '08129876543',
    orderType: 'dine_in',
    tableNumber: 'Meja 04',
    items: [
      {
        id: 'kro-01-c1',
        menuItem: MENU_ITEMS[0],
        quantity: 2,
        customization: {
          sugarLevel: 'less',
          iceLevel: 'normal',
          milkOption: 'oatmilk',
          selectedAddOns: ['extra_shot'],
          notes: 'Tolong jangan terlalu dingin',
        },
        itemPrice: 40000,
        totalPrice: 80000,
      },
      {
        id: 'kro-08-c1',
        menuItem: MENU_ITEMS[7],
        quantity: 1,
        customization: {
          sugarLevel: 'normal',
          iceLevel: 'none',
          milkOption: 'dairy',
          selectedAddOns: [],
          notes: 'Hangatkan sebentar',
        },
        itemPrice: 28000,
        totalPrice: 28000,
      },
    ],
    subtotal: 108000,
    tax: 10800,
    total: 118800,
    paymentMethod: 'qris',
    paymentStatus: 'paid',
    status: 'new',
    notes: 'Sedotan kertas 2 ya mas',
    createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(), // 4 mins ago
    updatedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
  },
  {
    id: 'KRO-799',
    customerName: 'Siti Rahma',
    customerPhone: '08138765432',
    orderType: 'dine_in',
    tableNumber: 'Meja 09',
    items: [
      {
        id: 'kro-02-c1',
        menuItem: MENU_ITEMS[1],
        quantity: 1,
        customization: {
          sugarLevel: 'normal',
          iceLevel: 'less',
          milkOption: 'dairy',
          selectedAddOns: [],
        },
        itemPrice: 34000,
        totalPrice: 34000,
      },
      {
        id: 'kro-10-c1',
        menuItem: MENU_ITEMS[9],
        quantity: 1,
        customization: {
          sugarLevel: 'normal',
          iceLevel: 'none',
          milkOption: 'dairy',
          selectedAddOns: [],
        },
        itemPrice: 32000,
        totalPrice: 32000,
      },
    ],
    subtotal: 66000,
    tax: 6600,
    total: 72600,
    paymentMethod: 'cash',
    paymentStatus: 'paid',
    status: 'brewing',
    notes: 'Saus aioli dipisah',
    createdAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
  },
  {
    id: 'KRO-795',
    customerName: 'Budi Santoso',
    customerPhone: '08571234567',
    orderType: 'takeaway',
    items: [
      {
        id: 'kro-06-c1',
        menuItem: MENU_ITEMS[5],
        quantity: 2,
        customization: {
          sugarLevel: 'low',
          iceLevel: 'normal',
          milkOption: 'dairy',
          selectedAddOns: [],
        },
        itemPrice: 33000,
        totalPrice: 66000,
      },
    ],
    subtotal: 66000,
    tax: 6600,
    total: 72600,
    paymentMethod: 'qris',
    paymentStatus: 'paid',
    status: 'ready',
    createdAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'KRO-788',
    customerName: 'Alya Natasha',
    customerPhone: '08123456789',
    orderType: 'dine_in',
    tableNumber: 'Meja 02',
    items: [
      {
        id: 'kro-04-c1',
        menuItem: MENU_ITEMS[3],
        quantity: 1,
        customization: {
          sugarLevel: 'none',
          iceLevel: 'none',
          milkOption: 'dairy',
          selectedAddOns: [],
        },
        itemPrice: 36000,
        totalPrice: 36000,
      },
      {
        id: 'kro-09-c1',
        menuItem: MENU_ITEMS[8],
        quantity: 1,
        customization: {
          sugarLevel: 'normal',
          iceLevel: 'none',
          milkOption: 'dairy',
          selectedAddOns: [],
        },
        itemPrice: 26000,
        totalPrice: 26000,
      },
    ],
    subtotal: 62000,
    tax: 6200,
    total: 68200,
    paymentMethod: 'card',
    paymentStatus: 'paid',
    status: 'completed',
    createdAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];
